# Reconciles the placeholder site_id UUIDs baked into out/fulcrum-migration/submissions/*.xml
# (generated by prepare-central-import.R) against the *real* entity IDs Central assigned when
# out/fulcrum-migration/sites_for_central_upload.csv was bulk-uploaded via Central's dataset
# "Upload CSV" page. See FULCRUM_MIGRATION.md step 3-4 for the full procedure.
#
# Why this step exists: Central's bulk entity CSV upload doesn't accept a caller-supplied entity
# ID (confirmed against a live Central 2026.x) -- it generates a fresh UUID per entity itself. But
# prepare-central-import.R had to invent a site_id UUID *before* any entity existed, so it could
# reference that site's future entity from every one of its historical submissions'
# <meta><entity id="..."> / <site_id>. Those placeholder UUIDs are real nowhere in Central. This
# script closes that gap: match placeholder site_id -> real entity ID by coordinates, then rewrite
# every submission in place before you upload them.
#
# Manual steps before running this:
#   1. Run prepare-central-import.R (writes sites_for_central_upload.csv +
#      site_id_placeholder_map.csv).
#   2. Upload sites_for_central_upload.csv via Central's dataset "Upload CSV" page.
#   3. From that dataset's entity list in Central's UI, download the resulting entity list and
#      save it as out/fulcrum-migration/entities_from_central.csv (exact filename).
#   4. Run this script.
#   5. Upload the (now-rewritten) out/fulcrum-migration/submissions/*.xml files.

library(tidyverse)
library(sf)

out_dir <- "out/fulcrum-migration"
submissions_dir <- file.path(out_dir, "submissions")

placeholder_path <- file.path(out_dir, "site_id_placeholder_map.csv")
central_path <- file.path(out_dir, "entities_from_central.csv")

if (!file.exists(placeholder_path)) {
  stop("Missing ", placeholder_path, " -- run prepare-central-import.R first.")
}
if (!file.exists(central_path)) {
  stop("Missing ", central_path, " -- download the entity list for this dataset from Central's ",
       "UI (after uploading sites_for_central_upload.csv) and save it at that exact path.")
}

placeholder_map <- read_csv(placeholder_path, show_col_types = FALSE)
central_entities <- read_csv(central_path, show_col_types = FALSE)

# Central's entity-list CSV download is not something this project has been able to verify the
# exact column name for against a live instance (see toad-monitoring-app/CLAUDE.md's "Entities:
# what's verified vs. assumed") -- it's `name` on the same-shaped CSV Central auto-attaches to a
# form's manifest (which this app's own fetchSiteList()/siteFromCsvRow() already parses that way),
# so that's tried first; a couple of other plausible headings are tried as fallback.
id_col_candidates <- c("name", "__id", "uuid", "id")
id_col <- id_col_candidates[id_col_candidates %in% names(central_entities)][1]
if (is.na(id_col)) {
  stop("Could not find an entity-ID column in ", central_path, " -- looked for one of: ",
       paste(id_col_candidates, collapse = ", "), ". Found columns: ",
       paste(names(central_entities), collapse = ", "),
       ". Open the file and check what Central actually called the ID column, then adjust ",
       "id_col_candidates above.")
}
message("Using '", id_col, "' as Central's entity ID column.")

central_entities <- central_entities |>
  rename(real_id = all_of(id_col))

if (!all(c("latitude", "longitude") %in% names(central_entities))) {
  stop("entities_from_central.csv is missing latitude/longitude columns -- can't match by ",
       "coordinates. Found columns: ", paste(names(central_entities), collapse = ", "))
}

# ---------- match central entities back to placeholder site_ids, by coordinates ----------
# Labels are NOT a safe match key here: this migration deliberately stopped clustering sites by
# name (see PROXIMITY_THRESHOLD_M's comment in prepare-central-import.R -- reused names like "Dam"
# were merging sites tens of km apart), so genuinely different sites can and do share an identical
# label. latitude/longitude, by contrast, were copied verbatim from site_id_placeholder_map.csv
# into the uploaded CSV and just echoed back by Central as the entity's own property values, so an
# exact (to floating-point noise) coordinate match is the reliable key. A wider nearest-neighbour
# fallback -- using the same 150m PROXIMITY_THRESHOLD_M this migration already uses to decide
# "same site" when clustering -- catches anything Central reformatted slightly on the way through.
EXACT_MATCH_TOLERANCE_M <- 1
NEAREST_MATCH_TOLERANCE_M <- 150

placeholder_sf <- placeholder_map |>
  st_as_sf(coords = c("longitude", "latitude"), crs = 4326, remove = FALSE)
central_sf <- central_entities |>
  st_as_sf(coords = c("longitude", "latitude"), crs = 4326, remove = FALSE)

nearest_idx <- st_nearest_feature(central_sf, placeholder_sf)
nearest_dist_m <- as.numeric(st_distance(central_sf, placeholder_sf[nearest_idx, ], by_element = TRUE))

candidate <- central_entities |>
  mutate(
    site_id = placeholder_map$site_id[nearest_idx],
    placeholder_label = placeholder_map$label[nearest_idx],
    match_distance_m = nearest_dist_m,
    match_type = case_when(
      match_distance_m <= EXACT_MATCH_TOLERANCE_M   ~ "exact",
      match_distance_m <= NEAREST_MATCH_TOLERANCE_M ~ "nearest",
      TRUE                                          ~ "unmatched"
    )
  )

# a placeholder site claimed as the nearest match by more than one central entity means two
# entities (e.g. an accidental double-upload) are competing for the same site -- refuse to guess
dupe_claims <- candidate |> filter(match_type != "unmatched") |> count(site_id) |> filter(n > 1)
if (nrow(dupe_claims) > 0) {
  stop("More than one Central entity matched the same placeholder site_id (within ",
       NEAREST_MATCH_TOLERANCE_M, "m) -- can't safely assign automatically: ",
       paste(dupe_claims$site_id, collapse = "; "),
       ". Check entities_from_central.csv for accidental duplicate uploads.")
}

matched <- candidate |> filter(match_type != "unmatched")
unmatched_central <- candidate |> filter(match_type == "unmatched")
unmatched_placeholder <- placeholder_map |> filter(!site_id %in% matched$site_id)

if (nrow(unmatched_central) > 0 || nrow(unmatched_placeholder) > 0) {
  write_csv(
    bind_rows(
      unmatched_central |> transmute(side = "central", real_id, label, latitude, longitude,
                                      nearest_placeholder_label = placeholder_label,
                                      nearest_distance_m = match_distance_m),
      unmatched_placeholder |> transmute(side = "placeholder", site_id, label, latitude, longitude)
    ),
    file.path(out_dir, "entity_id_crosswalk_unmatched.csv"), na = ""
  )
  message(nrow(unmatched_central), " Central entit(y/ies) and ", nrow(unmatched_placeholder),
          " placeholder site(s) didn't match within ", NEAREST_MATCH_TOLERANCE_M, "m -- see ",
          "entity_id_crosswalk_unmatched.csv. Submissions for unmatched sites are left untouched ",
          "(still referencing a placeholder ID) and must NOT be uploaded until resolved.")
}

n_nearest_only <- sum(matched$match_type == "nearest")
if (n_nearest_only > 0) {
  message(n_nearest_only, " site(s) matched only within ", NEAREST_MATCH_TOLERANCE_M,
          "m, not exactly -- worth a quick manual glance (see match_type/match_distance_m in ",
          "site_id_crosswalk.csv) in case a real nearby-but-different site got matched instead.")
}

write_csv(
  matched |> select(site_id, real_id, label_placeholder = placeholder_label, label_central = label,
                     match_type, match_distance_m),
  file.path(out_dir, "site_id_crosswalk.csv"), na = ""
)
message(nrow(matched), " of ", nrow(placeholder_map), " sites matched to a real Central entity ID.")

# ---------- rewrite submissions/*.xml and submissions_manifest.csv in place ----------

xml_files <- list.files(submissions_dir, pattern = "\\.xml$", full.names = TRUE)
n_rewritten <- 0
for (f in xml_files) {
  text <- read_file(f)
  # each file references exactly one site_id, in both <site_id>...</site_id> and
  # <entity ... id="...">, so a single global find/replace per matched placeholder is safe --
  # UUIDs are unique strings, no risk of an accidental partial match elsewhere in the file
  hit <- match(TRUE, map_lgl(matched$site_id, \(id) str_detect(text, fixed(id))))
  if (is.na(hit)) next # references a site_id with no crosswalk match -- left untouched, see above
  text <- str_replace_all(text, fixed(matched$site_id[hit]), matched$real_id[hit])
  write_file(text, f)
  n_rewritten <- n_rewritten + 1
}
message("Rewrote ", n_rewritten, " of ", length(xml_files), " submission XML files with real entity IDs.")
if (n_rewritten < length(xml_files)) {
  message(length(xml_files) - n_rewritten, " submission file(s) left untouched (no crosswalk ",
          "match) -- do not upload those until their site is resolved.")
}

manifest_path <- file.path(out_dir, "submissions_manifest.csv")
if (file.exists(manifest_path)) {
  manifest <- read_csv(manifest_path, show_col_types = FALSE)
  manifest <- manifest |>
    left_join(matched |> select(site_id, real_id), by = "site_id") |>
    mutate(site_id = coalesce(real_id, site_id)) |>
    select(-real_id)
  write_csv(manifest, manifest_path, na = "")
  message("Updated site_id in ", manifest_path, " to real entity IDs where matched.")
}

message("Done. Upload out/fulcrum-migration/submissions/*.xml for sites with a real_id in ",
        "site_id_crosswalk.csv; leave the rest until entity_id_crosswalk_unmatched.csv is resolved.")
